// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
// await Firebase.initializeApp(
//     options = DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZy3LPjqkT9ASUaP9XdwRXKmEVKmumd_c',
    appId: '1:84598405696:android:cffef43412b04be1003da5',
    messagingSenderId: '84598405696',
    projectId: 'tabpay-e9118',
    databaseURL:
        'https://tabpay-e9118-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabpay-e9118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfB2Vl5SMv847Lbptwnqrx9c1RdOp880A',
    appId: '1:84598405696:ios:d905dcf75daecfbd003da5',
    messagingSenderId: '84598405696',
    projectId: 'tabpay-e9118',
    databaseURL:
        'https://tabpay-e9118-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabpay-e9118.appspot.com',
    iosBundleId: 'com.example.tabpayApp',
  );
}
